# Generated by Django 3.0.8 on 2020-07-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('emailid', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=100)),
                ('confirmpass', models.CharField(max_length=100)),
            ],
        ),
    ]
